travis:
  secure:
    BINSTAR_TOKEN: wAP4Lc3SmBAVDbj7EiKO92ASmBuxKlH2siYQLlCLysYm9HM4i2tc52K9XaV1VCsJw3ZWvYa9sy9wtEU61arhB1u0iXVfGuX17/iZBId+yguDEpAO9bE48FymTXpwj4NxDif2KdU7fc91TApTn9i/tmXUjQXX0MNUAr/1yCoAdR1xp8PbEntsJHdu5Xip+W7OusxhjBhaQmNeW8TZAbzLLmA7UgTvTELdwCdEMQCZhtv1Q6nWmchVycRnSWlRwj+VBk9vokBMtbprUD851hXeFKSwUew9GR84k/AsE+161MLGizz7EAmKln+yavOcAvynh/UsmjFrqkjEpaa15QakcOcWZkvuFqVmxlMtbN5s2ZQyCNu1W27CtjAtT3fKDhYhdehEKVqvO8ifdnTs0G1VllVBBRuarrso+K+cOSZASI5CFAVwQbi+5xwec0MS82XERO3dIt3d2CoL0e9HxbhreD2Hh0YXB0wXjBBuRvK6riydznZrnV9Apz9ewWYS6A+/UxqOGeK9quY9EVHeSChxPezTZRm84XEdAZsWB4bM5BH7ig1xb0RYy9CTC3z4VGxnQkwGv7JIz3L01GinXbjIGPNaWzYTb5tpw7sLrmVwYgXf1HlJNQsMSKT2Z3jm4dGeJ2f4xPBtTxPOw+7SK7UOh/mAKbLvoWoyWe1Z6Vo/MK8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
